---
apiVersion: v1
kind: Service
metadata:
  name: demo-grafana
  namespace: monitoring
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.55.65
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  sessionAffinity: ClientIP
  type: LoadBalancer
